-- Auto-generated by IVISimplicialGrid
-- This file is a scaffold; replace stubs with real formalizations.

-- >>> IVI_EQUATION E_180332dda5ac45b5 BEGIN
/-- Proposition derived from: Define triangle time as relational closure -/
theorem define_triangle_time_as_relational_closure : True := by
  trivial

-- <<< IVI_EQUATION E_180332dda5ac45b5 END

