-- Auto-generated by IVISimplicialGrid
-- This file is a scaffold; replace stubs with real formalizations.

-- >>> IVI_EQUATION E_38d7f9dee0a41ed0 BEGIN
/-- Proposition derived from: def extract_symbols: def extract_symbols(text) -> List[str] -/
theorem def_extract_symbols_def_extract_symbols_text_list : True := by
  trivial

-- <<< IVI_EQUATION E_38d7f9dee0a41ed0 END

-- >>> IVI_EQUATION E_01a2dd24b79ed3bc BEGIN
/-- Proposition derived from: def derive_claims_from_text: def derive_claims_from_text(text, prov) -> List[LogicClaim] -/
theorem def_derive_claims_from_text_def_derive_claims : True := by
  trivial

-- <<< IVI_EQUATION E_01a2dd24b79ed3bc END

-- >>> IVI_EQUATION E_8a17348ffc02828b BEGIN
/-- Proposition derived from: extract_symbols complexity=7, candidate for refactor -/
theorem extract_symbols_complexity_7_candidate_for_refactor : True := by
  trivial

-- <<< IVI_EQUATION E_8a17348ffc02828b END

-- >>> IVI_EQUATION E_fe67f0584c9f5ff4 BEGIN
/-- Proposition derived from: if derive then __future__ -/
theorem if_derive_then_future : True := by
  trivial

-- <<< IVI_EQUATION E_fe67f0584c9f5ff4 END

-- >>> IVI_EQUATION E_89b4a6db3c0b718f BEGIN
/-- Proposition derived from: if derive then re -/
theorem if_derive_then_re : True := by
  trivial

-- <<< IVI_EQUATION E_89b4a6db3c0b718f END

-- >>> IVI_EQUATION E_1765b8dbb3a327db BEGIN
/-- Proposition derived from: if derive then typing -/
theorem if_derive_then_typing : True := by
  trivial

-- <<< IVI_EQUATION E_1765b8dbb3a327db END

-- >>> IVI_EQUATION E_750309f68446c7f1 BEGIN
/-- Proposition derived from: if derive then ir -/
theorem if_derive_then_ir : True := by
  trivial

-- <<< IVI_EQUATION E_750309f68446c7f1 END

-- >>> IVI_EQUATION E_2b19aa0a54383535 BEGIN
/-- Proposition derived from: if extract_symbols then add -/
theorem if_extract_symbols_then_add : True := by
  trivial

-- <<< IVI_EQUATION E_2b19aa0a54383535 END

-- >>> IVI_EQUATION E_0a41057f3c7392a8 BEGIN
/-- Proposition derived from: if extract_symbols then append -/
theorem if_extract_symbols_then_append : True := by
  trivial

-- <<< IVI_EQUATION E_0a41057f3c7392a8 END

-- >>> IVI_EQUATION E_b9fb1d4489b0b879 BEGIN
/-- Proposition derived from: if extract_symbols then finditer -/
theorem if_extract_symbols_then_finditer : True := by
  trivial

-- <<< IVI_EQUATION E_b9fb1d4489b0b879 END

-- >>> IVI_EQUATION E_628df02e885b768b BEGIN
/-- Proposition derived from: if extract_symbols then group -/
theorem if_extract_symbols_then_group : True := by
  trivial

-- <<< IVI_EQUATION E_628df02e885b768b END

-- >>> IVI_EQUATION E_cab61900433fd8be BEGIN
/-- Proposition derived from: if extract_symbols then lower -/
theorem if_extract_symbols_then_lower : True := by
  trivial

-- <<< IVI_EQUATION E_cab61900433fd8be END

-- >>> IVI_EQUATION E_dbe3660b0edf10ac BEGIN
/-- Proposition derived from: if derive_claims_from_text then append -/
theorem if_derive_claims_from_text_then_append : True := by
  trivial

-- <<< IVI_EQUATION E_dbe3660b0edf10ac END

-- >>> IVI_EQUATION E_6d3075d129e92a30 BEGIN
/-- Proposition derived from: if derive_claims_from_text then extract_symbols -/
theorem if_derive_claims_from_text_then_extract_symbols : True := by
  trivial

-- <<< IVI_EQUATION E_6d3075d129e92a30 END

-- >>> IVI_EQUATION E_7f52bb62811b5465 BEGIN
/-- Proposition derived from: if derive_claims_from_text then group -/
theorem if_derive_claims_from_text_then_group : True := by
  trivial

-- <<< IVI_EQUATION E_7f52bb62811b5465 END

-- >>> IVI_EQUATION E_6eb4db87ce708dfa BEGIN
/-- Proposition derived from: if derive_claims_from_text then make_claim -/
theorem if_derive_claims_from_text_then_make_claim : True := by
  trivial

-- <<< IVI_EQUATION E_6eb4db87ce708dfa END

-- >>> IVI_EQUATION E_eeb6b3187ca30245 BEGIN
/-- Proposition derived from: if derive_claims_from_text then match -/
theorem if_derive_claims_from_text_then_match : True := by
  trivial

-- <<< IVI_EQUATION E_eeb6b3187ca30245 END

